apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-bbmn
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-bbmn
    app.kubernetes.io/part-of: tkrw-pr712-0075-0020-app
  name: devfile-sample-bbmn
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-bbmn
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-bbmn
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0020-tenant/tkrw-pr712-0075-0020-app/devfile-sample-bbmn@sha256:9ab44d609e953df8ef79833d3ad2089518e133df658e2296b4e34f53c57a9730
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
