apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-bbmn
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0020-tenant/tkrw-pr712-0075-0020-app/devfile-sample-bbmn@sha256:9ab44d609e953df8ef79833d3ad2089518e133df658e2296b4e34f53c57a9730
        name: my-nodejs
        resources: {}
status: {}
